language: android
os:
  - linux
  - osx
sudo: required
before_install:
  - ./dependencies.sh
before_script:
  - . ./setenv.sh
script:
  - travis_wait 30 ./travis.sh
after_failure:
  - cat emulator.log
  - cat logcat.log
